version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    command:
      - python3 
      - manage.py
      - start

  prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/sites-enabled/nginx.conf
      - ./uwsgi.ini:/etc/uwsgi/apps-enabled/uwsgi.ini
      - ./log:/var/log/nginx
      - ./log:/var/log/uwsgi/app
      # - /etc/letsencrpt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command:
      - python3 
      - manage.py
      - build