version: '3'

services:
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./:/app
      - ./config/production/celery.conf:/etc/supervisor/conf.d/celery.conf
      - ./log:/app/log
    command: >
      sh -c " 
        rm celerybeat-schedule.db
        rm celerybeat.pid
        python3 -m pip install -U -r requirements.txt 
        service supervisor start 
        tail -f /dev/null
      "