# Generated by Django 3.1.8 on 2021-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
