# Generated by Django 2.2.8 on 2020-02-05 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boarditem_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='author_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
