# Generated by Django 3.1.8 on 2021-04-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='refresh_token',
        ),
    ]
