# Generated by Django 2.2.8 on 2020-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boardcomment_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
