# Generated by Django 2.2.8 on 2020-02-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shopproduct_conetnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='conetnt',
            new_name='content',
        ),
    ]
