# Generated by Django 2.2.8 on 2020-02-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200208_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='product',
            field=models.ManyToManyField(blank=True, to='api.ShopProduct'),
        ),
    ]
