# Generated by Django 2.2.8 on 2020-02-08 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200208_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppayment',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
