# Generated by Django 2.2.8 on 2020-02-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
