# Generated by Django 2.2.8 on 2020-02-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shoppayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppayment',
            name='buyer_addr',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='buyer_postcode',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='buyer_tel',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='paid_amount',
        ),
    ]
