# Generated by Django 2.2.8 on 2020-02-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200209_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppayment',
            name='vbank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
