# Generated by Django 2.2.8 on 2020-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shoppayment_vbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '상점 구독내역',
            },
        ),
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '상점 구독카드',
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '상점 구독',
            },
        ),
        migrations.AlterModelOptions(
            name='boardcomment',
            options={'verbose_name_plural': '게시판 댓글'},
        ),
        migrations.AlterModelOptions(
            name='boarditem',
            options={'verbose_name_plural': '게시판 글'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name_plural': '상점 장바구니'},
        ),
        migrations.AlterModelOptions(
            name='shoppayment',
            options={'verbose_name_plural': '상점 결재내역'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name_plural': '상점 상품'},
        ),
    ]
