# Generated by Django 2.2.8 on 2020-02-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200206_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='boarditem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BoardItem'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
