# Generated by Django 2.2.8 on 2020-02-09 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200209_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbilling',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopbilling',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopbilling',
            name='next_pay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopcard',
            name='customer_uid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
