# Generated by Django 2.2.8 on 2020-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200209_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='name',
            field=models.CharField(default='삼성카드', max_length=100),
            preserve_default=False,
        ),
    ]
