# Generated by Django 2.2.8 on 2020-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shopcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='buyer_email',
            field=models.CharField(default='email', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcard',
            name='buyer_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcard',
            name='buyer_tel',
            field=models.CharField(default='tel', max_length=100),
            preserve_default=False,
        ),
    ]
