# Generated by Django 2.2.8 on 2020-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200209_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbilling',
            name='imp_uid',
            field=models.CharField(default='imp_uid', max_length=100),
            preserve_default=False,
        ),
    ]
