# Generated by Django 2.2.8 on 2020-02-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shopbilling_merchant_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarditem',
            name='author_name',
        ),
    ]
