# Generated by Django 2.2.8 on 2020-02-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_boarditem_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcomment',
            name='author_name',
        ),
    ]
