# Generated by Django 2.2.8 on 2020-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_taskwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskwork',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
