# Generated by Django 2.2.8 on 2020-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200214_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default='web', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='extra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
