# Generated by Django 2.2.8 on 2020-02-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200219_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorusage',
            name='server',
        ),
        migrations.CreateModel(
            name='MonitorMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MonitorServer')),
            ],
        ),
        migrations.AddField(
            model_name='monitorusage',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MonitorMemory'),
        ),
    ]
