# Generated by Django 2.2.10 on 2020-02-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200219_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorserver',
            old_name='mac_address',
            new_name='address',
        ),
    ]
